image:
  repository: rnrmf
  name: kiwi-order-service
  pullPolicy: IfNotPresent
  tag: 152
replicaCount: 1
containerPort: 8100
protocol: TCP
service:
  type: ClusterIP
  port: 8100
namespace: order
order_mysql_url: mysql-0.order-mysql-service.order.svc.cluster.local
