server:
  port: 8090
spring:
  application:
    name: user
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_URL:localhost}:8888

---
springdoc:
  api-docs:
    enabled: true
    path: /user/v3/api-docs
  swagger-ui:
    enabled: true