server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_URL:localhost}:8888

---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: User Service
        url: /user/v3/api-docs
      - name: Store Service
        url: /store/v3/api-docs