spring:
  profiles:
    default: local
  config:
    import: secret/token.yml
---
spring:
  config:
    activate:
      on-profile: local
GATEWAY:
  USER_SERVICE_URL: http://localhost:8090
  STORE_SERVICE_URL: http://localhost:8095

---
spring:
  config:
    activate:
      on-profile: prod

GATEWAY:
  USER_SERVICE_URL: http://user-service-app.user.svc.cluster.local:8090
  STORE_SERVICE_URL: http://store-service-app.store.svc.cluster.local:8095
