spring:
  profiles:
    default: local
gateway:
  url:
    user-service: ${USER-SERVICE-URL}
    store-service: ${STORE-SERVICE-URL}
---
spring:
  config:
    activate:
      on-profile: local
    import: secret/application-local.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: secret/application-prod.yml