replicaCount: 1
image:
  repository: rnrmf
  name: store-service-app
  pullPolicy: IfNotPresent
  tag: 224
containerPort: 8095
springEnv:
  storeMysqlUrl: mysql-0.mysql.store.svc.cluster.local
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
namespace: store
securityContext: {}
serviceType: ClusterIP
mysql:
  host: mysql
  port: 3306
  database: dev
  username: root
  password: root
service:
  type: ClusterIP
  port: 8090
springApp:
  env:
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/dev"
    SPRING_DATASOURCE_USERNAME: "root"
    SPRING_DATASOURCE_PASSWORD: "root"
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
