image:
  repository: rnrmf
  name: kiwi-settlement-service
  pullPolicy: IfNotPresent
  tag: latest
replicaCount: 1
containerPort: 8310
protocol: TCP
service:
  type: ClusterIP
  port: 8310
namespace: settlement
settlement_mysql_url: mysql-0.mysql.settlement.svc.cluster.local
