apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}-app
    spec:
      containers:
        - name: user-service-container
          image: "{{ .Values.image.repository}}/{{ .Values.image.name }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: CONFIG_SERVICE_URL
              value: config-server-app-service.config.svc.cluster.local
            - name: USER_MYSQL_URL
              value: {{ .Values.springEnv.userMysqlUrl}}
            - name: PROFILE
              value: prod
            - name: KAFKA_URL
              value: kraft-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: NOTIFICATION_SERVICE_URL
              value: notification-server-app.notification.svc.cluster.local
            - name: DOMAIN_NAME
              value: i12a404.p.ssafy.io
            - name: USER_SERVICE_REDIS_NAME
              value: redis-0.redis.user.svc.cluster.local
            - name: USER_SERVICE_REDIS_PORT
              value: "6379"